# Fabric Properties (verificati su https://github.com/FabricMC/fabric-example-mod/tree/26.2)
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod info
mod_version=1.0.0
maven_group=com.example
archives_base_name=autorejoin

# Dependencies
fabric_api_version=0.156.0+26.2

org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
